language: julia
julia:
    - 0.6
    - 0.7
    - 1.0
    - release
    - nightly
os:
    - linux
    - osx
coveralls: true
codecov: true
matrix:
    fast_finish: true
install:
    - echo "overwrite?"
