language: julia
julia:
    - 0.3
    - 0.4
    - nightly
os:
    - linux
    - osx
sudo: false
notifications:
    email: false
script:
     - julia -e 'Pkg.add("WinRPM")'
     - julia -e 'Pkg.build()'
     - julia -e '@time Pkg.build()'
#    - julia -e 'Base.runtests()'
#    - julia-debug -e 'Base.runtests()'
#    - julia -e 'Base.runtests("pkg")'
#    - julia-debug -e 'Base.runtests("pkg")'
